# Generated by Django 4.2.17 on 2024-12-19 13:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0004_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='currency',
            field=models.IntegerField(blank=True, choices=[(0, '€'), (1, '£'), (2, '$')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
